# test_root: [/path/to/dataset/split/1/for/feature/extraction, /path/to/dataset/split/2/for/feature/extraction] #------------------send this one in the command line
exp_name: ""
# clusters_out_root: /path/to/save/cluster/results
# features_out_root: /path/to/save/feature/results #i will save it next to the original image directly
# vis_out_root: "" 
n_clusters: 12
name_depth: 3

image_size: 256
img_pad: 4

n_images_cluster: 50
metric: cos

use_pca: True
pca_dim: 16 #64
save_pca_features: True
load_pca_path: '/viscam/projects/video_animals/husam/preprocessing/data/Final_combined/pca.faiss'

save_clusters: True

dim_in_filename: True

save_visuals: True

normalize_features: True

device: cuda #cuda:0
faiss_device: 1

shuffle_data: True
batch_size: 6

use_saliency: True
load_mask: True


img_postfix_test: _rgb.png
mask_postfix_test: _mask.png

img_postfix_train: _rgb.png
mask_postfix_train: _mask.png


# train_root: [/path/to/dataset/split/1/for/training/pca, /path/to/dataset/split/2/for/training/pca] #------------------send this one in the command line
# results_info_root: /viscam/projects/video_animals/husam/preprocessing/data/Final #save pca mat #------------------send this one in the command line


